"""ai fields new

Revision ID: 0082df11e837
Revises: 16f6d3611d22
Create Date: 2026-04-18 09:18:45.203968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0082df11e837'
down_revision: Union[str, Sequence[str], None] = '16f6d3611d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_items', sa.Column('subtype', sa.String(), nullable=True))
    op.add_column('academic_items', sa.Column('action_type', sa.String(), nullable=True))
    op.add_column('academic_items', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('academic_items', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_academic_items_subtype'), 'academic_items', ['subtype'], unique=False)
    op.add_column('gmail_messages', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('gmail_messages', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('gmail_messages', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_messages', 'next_retry_at')
    op.drop_column('gmail_messages', 'last_error')
    op.drop_column('gmail_messages', 'retry_count')
    op.drop_index(op.f('ix_academic_items_subtype'), table_name='academic_items')
    op.drop_column('academic_items', 'event_date')
    op.drop_column('academic_items', 'summary')
    op.drop_column('academic_items', 'action_type')
    op.drop_column('academic_items', 'subtype')
    # ### end Alembic commands ###
