"""add_ai_fields_to_gmail_messages

Revision ID: 049e266e0428
Revises: 6de113e59a10
Create Date: 2026-02-13 08:44:37.978243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049e266e0428'
down_revision: Union[str, Sequence[str], None] = '6de113e59a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_messages', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('gmail_messages', sa.Column('ai_label_topic', sa.String(), nullable=True))
    op.add_column('gmail_messages', sa.Column('ai_label_urgency', sa.String(), nullable=True))
    op.add_column('gmail_messages', sa.Column('ai_label_source', sa.String(), nullable=True))
    op.add_column('gmail_messages', sa.Column('ai_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_messages', 'ai_processed')
    op.drop_column('gmail_messages', 'ai_label_source')
    op.drop_column('gmail_messages', 'ai_label_urgency')
    op.drop_column('gmail_messages', 'ai_label_topic')
    op.drop_column('gmail_messages', 'ai_summary')
    # ### end Alembic commands ###
