"""add_normalized_topic_to_academic_items

Revision ID: 0d421ddd8350
Revises: eaf8f9789c2a
Create Date: 2026-04-19 07:12:48.320193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d421ddd8350'
down_revision: Union[str, Sequence[str], None] = 'eaf8f9789c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_items', sa.Column('normalized_topic', sa.String(), nullable=True))
    op.create_index(op.f('ix_academic_items_normalized_topic'), 'academic_items', ['normalized_topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_items_normalized_topic'), table_name='academic_items')
    op.drop_column('academic_items', 'normalized_topic')
    # ### end Alembic commands ###
