"""Add AcademicItem, DomainStats

Revision ID: 2b9620d703df
Revises: 8652b8dbf62d
Create Date: 2026-03-16 17:48:01.186672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9620d703df'
down_revision: Union[str, Sequence[str], None] = '8652b8dbf62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_email_id', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('professor', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('academic_score', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_items_entity_type'), 'academic_items', ['entity_type'], unique=False)
    op.create_index(op.f('ix_academic_items_id'), 'academic_items', ['id'], unique=False)
    op.create_index(op.f('ix_academic_items_source_email_id'), 'academic_items', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_academic_items_uid'), 'academic_items', ['uid'], unique=False)
    op.create_table('domain_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('total_emails', sa.Integer(), nullable=True),
    sa.Column('deadline_count', sa.Integer(), nullable=True),
    sa.Column('high_score_count', sa.Integer(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_stats_domain'), 'domain_stats', ['domain'], unique=True)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_email_id', sa.String(), nullable=True),
    sa.Column('trigger_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_source_email_id'), 'follow_ups', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_trigger_at'), 'follow_ups', ['trigger_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_ups_trigger_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_source_email_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_domain_stats_domain'), table_name='domain_stats')
    op.drop_table('domain_stats')
    op.drop_index(op.f('ix_academic_items_uid'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_source_email_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_entity_type'), table_name='academic_items')
    op.drop_table('academic_items')
    # ### end Alembic commands ###
