"""latest changes

Revision ID: 31843f5a52cc
Revises: 004_drop_domain_stats
Create Date: 2026-03-19 14:27:42.184693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31843f5a52cc'
down_revision: Union[str, Sequence[str], None] = '004_drop_domain_stats'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'source_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="'institution' | 'student' | 'external_academic' | 'external_misc'",
               existing_nullable=False)
    op.alter_column('gmail_messages', 'academic_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('gmail_sync_status', 'new_messages_count')
    op.alter_column('user_domain_preferences', 'is_trusted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='User marked this domain as important',
               existing_nullable=False)
    op.alter_column('user_domain_preferences', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='User blocked this domain',
               existing_nullable=False)
    op.drop_index(op.f('idx_user_domain'), table_name='user_domain_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_domain'), 'user_domain_preferences', ['user_id', 'domain'], unique=False)
    op.alter_column('user_domain_preferences', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               comment='User blocked this domain',
               existing_nullable=False)
    op.alter_column('user_domain_preferences', 'is_trusted',
               existing_type=sa.BOOLEAN(),
               comment='User marked this domain as important',
               existing_nullable=False)
    op.add_column('gmail_sync_status', sa.Column('new_messages_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('gmail_messages', 'academic_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('domains', 'source_type',
               existing_type=sa.VARCHAR(),
               comment="'institution' | 'student' | 'external_academic' | 'external_misc'",
               existing_nullable=False)
    # ### end Alembic commands ###
