"""Add incremental sync fields to gmail_sync_status

Revision ID: 324b11bf05e3
Revises: 10aa7e23032d
Create Date: 2026-01-24 10:53:30.939126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324b11bf05e3'
down_revision: Union[str, Sequence[str], None] = '10aa7e23032d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sync_status', sa.Column('last_sync_date', sa.DateTime(), nullable=True))
    op.add_column('gmail_sync_status', sa.Column('total_messages_synced', sa.Integer(), nullable=True))
    op.add_column('gmail_sync_status', sa.Column('next_page_token', sa.String(), nullable=True))
    op.add_column('gmail_sync_status', sa.Column('sync_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sync_status', 'sync_type')
    op.drop_column('gmail_sync_status', 'next_page_token')
    op.drop_column('gmail_sync_status', 'total_messages_synced')
    op.drop_column('gmail_sync_status', 'last_sync_date')
    # ### end Alembic commands ###
