"""add admin_connected field to users

Revision ID: 57f6b8017058
Revises: 6a14bf04f61a
Create Date: 2026-04-06 19:05:22.628243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f6b8017058'
down_revision: Union[str, Sequence[str], None] = '6a14bf04f61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_connected')
    # ### end Alembic commands ###
