"""schema_sanity_check

Revision ID: 5aa92243160b
Revises: e1fd433944f4
Create Date: 2026-02-26 13:38:24.915923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa92243160b'
down_revision: Union[str, Sequence[str], None] = 'e1fd433944f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_messages', sa.Column('ai_status', sa.String(), nullable=True))
    op.alter_column('gmail_messages', 'normalized_topic',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'OTHER'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gmail_messages', 'normalized_topic',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.drop_column('gmail_messages', 'ai_status')
    # ### end Alembic commands ###
