"""add reauth fields to users

Revision ID: 6a14bf04f61a
Revises: ded6d6cb85e3
Create Date: 2026-04-06 18:59:23.198481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a14bf04f61a'
down_revision: Union[str, Sequence[str], None] = 'ded6d6cb85e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
