"""add ai columns

Revision ID: 6de113e59a10
Revises: 8bd7f1559ebd
Create Date: 2026-02-12 12:47:58.243988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de113e59a10'
down_revision: Union[str, Sequence[str], None] = '8bd7f1559ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # gmail_messages: create if missing, otherwise skip
    if 'gmail_messages' not in inspector.get_table_names():
        op.create_table('gmail_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('uid', sa.String(), nullable=True),
            sa.Column('gmail_id', sa.String(), nullable=True),
            sa.Column('thread_id', sa.String(), nullable=True),
            sa.Column('sender', sa.String(), nullable=True),
            sa.Column('subject', sa.String(), nullable=True),
            sa.Column('snippet', sa.Text(), nullable=True),
            sa.Column('body_html', sa.Text(), nullable=True),
            sa.Column('body_text', sa.Text(), nullable=True),
            sa.Column('internal_date', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    # Ensure indexes exist
    existing_idx = {idx['name'] for idx in inspector.get_indexes('gmail_messages')} if 'gmail_messages' in inspector.get_table_names() else set()
    if 'ix_gmail_messages_gmail_id' not in existing_idx:
        op.create_index(op.f('ix_gmail_messages_gmail_id'), 'gmail_messages', ['gmail_id'], unique=True)
    if 'ix_gmail_messages_uid' not in existing_idx:
        op.create_index(op.f('ix_gmail_messages_uid'), 'gmail_messages', ['uid'], unique=False)

    # gmail_sync_status: create if missing
    if 'gmail_sync_status' not in inspector.get_table_names():
        op.create_table('gmail_sync_status',
            sa.Column('uid', sa.String(), nullable=False),
            sa.Column('status', sa.String(), nullable=True),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('finished_at', sa.DateTime(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('last_sync_date', sa.DateTime(), nullable=True),
            sa.Column('total_messages_synced', sa.Integer(), nullable=True),
            sa.Column('next_page_token', sa.String(), nullable=True),
            sa.Column('sync_type', sa.String(), nullable=True),
            sa.Column('last_history_id', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('uid')
        )

    # users index: create only if users table exists and index missing
    if 'users' in inspector.get_table_names():
        users_idx = {idx['name'] for idx in inspector.get_indexes('users')}
        if 'ix_users_uid' not in users_idx:
            op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('gmail_sync_status')
    op.drop_index(op.f('ix_gmail_messages_uid'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_gmail_id'), table_name='gmail_messages')
    op.drop_table('gmail_messages')
    # ### end Alembic commands ###
