"""new history column

Revision ID: 82cde58a7208
Revises: 9e65cd83c2d7
Create Date: 2026-01-26 14:20:09.615897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cde58a7208'
down_revision: Union[str, Sequence[str], None] = '9e65cd83c2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sync_status', sa.Column('last_history_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sync_status', 'last_history_id')
    # ### end Alembic commands ###
