"""add email column to oauth_tokens

Revision ID: 8bd7f1559ebd
Revises: 281ce5afae6f
Create Date: 2026-02-12 11:49:58.582961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd7f1559ebd'
down_revision: Union[str, Sequence[str], None] = '281ce5afae6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Migration corrected: this revision should add an `email` column to oauth_tokens
    # if the table already exists. Some environments already have oauth_tokens/users
    # created by earlier revisions; guard against DuplicateTable errors.
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'oauth_tokens' in inspector.get_table_names():
        # Add 'email' column if it doesn't exist
        cols = [c['name'] for c in inspector.get_columns('oauth_tokens')]
        if 'email' not in cols:
            op.add_column('oauth_tokens', sa.Column('email', sa.String(), nullable=True))
    else:
        # If oauth_tokens table is missing, create it with the expected columns
        op.create_table('oauth_tokens',
            sa.Column('uid', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('refresh_token', sa.Text(), nullable=False),
            sa.Column('scopes', sa.Text(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.Column('token_type', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('uid')
        )

    # Users table: create only if missing
    if 'users' not in inspector.get_table_names():
        op.create_table('users',
            sa.Column('uid', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('name', sa.String(), nullable=True),
            sa.Column('branch', sa.String(), nullable=True),
            sa.Column('semester', sa.Integer(), nullable=True),
            sa.Column('sid', sa.String(), nullable=True),
            sa.Column('profile_completed', sa.Boolean(), nullable=True),
            sa.Column('oauth_connected', sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint('uid'),
            sa.UniqueConstraint('email')
        )
        op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('oauth_tokens')
    # ### end Alembic commands ###
