"""create broadcasts table (detect)

Revision ID: 94c996b306fb
Revises: 6e29cf7febcb
Create Date: 2026-03-23 08:01:18.939077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c996b306fb'
down_revision: Union[str, Sequence[str], None] = '6e29cf7febcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_label_topic', sa.String(), nullable=True),
    sa.Column('ai_label_urgency', sa.String(), nullable=True),
    sa.Column('ai_label_source', sa.String(), nullable=True),
    sa.Column('deadline_iso', sa.DateTime(), nullable=True),
    sa.Column('deadline_confidence', sa.String(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_broadcast_id'), 'broadcasts', ['broadcast_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcasts_broadcast_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
