"""initial clean schema

Revision ID: b930dc7092c2
Revises: 
Create Date: 2026-04-10 20:38:35.564078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b930dc7092c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_email_id', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('professor', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('academic_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('source_signals_json', sa.Text(), nullable=True),
    sa.Column('merge_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_items_entity_type'), 'academic_items', ['entity_type'], unique=False)
    op.create_index(op.f('ix_academic_items_id'), 'academic_items', ['id'], unique=False)
    op.create_index(op.f('ix_academic_items_merge_key'), 'academic_items', ['merge_key'], unique=False)
    op.create_index(op.f('ix_academic_items_source_email_id'), 'academic_items', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_academic_items_status'), 'academic_items', ['status'], unique=False)
    op.create_index(op.f('ix_academic_items_uid'), 'academic_items', ['uid'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_label_topic', sa.String(), nullable=True),
    sa.Column('ai_label_urgency', sa.String(), nullable=True),
    sa.Column('ai_label_source', sa.String(), nullable=True),
    sa.Column('deadline_iso', sa.DateTime(), nullable=True),
    sa.Column('deadline_confidence', sa.String(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_broadcast_id'), 'broadcasts', ['broadcast_id'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('is_default_trusted', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=True)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_email_id', sa.String(), nullable=True),
    sa.Column('trigger_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_source_email_id'), 'follow_ups', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_trigger_at'), 'follow_ups', ['trigger_at'], unique=False)
    op.create_table('gmail_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('gmail_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('internal_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_label_topic', sa.String(), nullable=True),
    sa.Column('ai_label_urgency', sa.String(), nullable=True),
    sa.Column('ai_label_source', sa.String(), nullable=True),
    sa.Column('unidash_broadcast_id', sa.String(), nullable=True),
    sa.Column('deadline_iso', sa.DateTime(), nullable=True),
    sa.Column('deadline_confidence', sa.String(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('normalized_topic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_messages_gmail_id'), 'gmail_messages', ['gmail_id'], unique=True)
    op.create_index(op.f('ix_gmail_messages_uid'), 'gmail_messages', ['uid'], unique=False)
    op.create_index(op.f('ix_gmail_messages_unidash_broadcast_id'), 'gmail_messages', ['unidash_broadcast_id'], unique=False)
    op.create_table('gmail_sync_status',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.Column('total_messages_synced', sa.Integer(), nullable=True),
    sa.Column('next_page_token', sa.String(), nullable=True),
    sa.Column('sync_type', sa.String(), nullable=True),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('oauth_tokens',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_domain_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_user_domain')
    )
    op.create_index(op.f('ix_user_domain_preferences_domain'), 'user_domain_preferences', ['domain'], unique=False)
    op.create_index(op.f('ix_user_domain_preferences_user_id'), 'user_domain_preferences', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('oauth_connected', sa.Boolean(), nullable=True),
    sa.Column('admin_connected', sa.Boolean(), nullable=True),
    sa.Column('reauth_required', sa.Boolean(), nullable=True),
    sa.Column('reauth_required_at', sa.DateTime(), nullable=True),
    sa.Column('reauth_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_domain_preferences_user_id'), table_name='user_domain_preferences')
    op.drop_index(op.f('ix_user_domain_preferences_domain'), table_name='user_domain_preferences')
    op.drop_table('user_domain_preferences')
    op.drop_table('oauth_tokens')
    op.drop_table('gmail_sync_status')
    op.drop_index(op.f('ix_gmail_messages_unidash_broadcast_id'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_uid'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_gmail_id'), table_name='gmail_messages')
    op.drop_table('gmail_messages')
    op.drop_index(op.f('ix_follow_ups_trigger_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_source_email_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_broadcasts_broadcast_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_academic_items_uid'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_status'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_source_email_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_merge_key'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_entity_type'), table_name='academic_items')
    op.drop_table('academic_items')
    # ### end Alembic commands ###
