"""add academic consolidation fields

Revision ID: c110f9dfdf6c
Revises: c1a9fb1d2a44
Create Date: 2026-04-07 14:58:10.974980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c110f9dfdf6c'
down_revision: Union[str, Sequence[str], None] = 'c1a9fb1d2a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_items', sa.Column('source_count', sa.Integer(), nullable=True))
    op.add_column('academic_items', sa.Column('source_signals_json', sa.Text(), nullable=True))
    op.add_column('academic_items', sa.Column('merge_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_academic_items_merge_key'), 'academic_items', ['merge_key'], unique=False)
    op.create_index(op.f('ix_academic_items_status'), 'academic_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_items_status'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_merge_key'), table_name='academic_items')
    op.drop_column('academic_items', 'merge_key')
    op.drop_column('academic_items', 'source_signals_json')
    op.drop_column('academic_items', 'source_count')
    # ### end Alembic commands ###
