"""add academic entity summary

Revision ID: c859de9500e6
Revises: d98c521b27f0
Create Date: 2026-04-29 16:16:44.277747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c859de9500e6'
down_revision: Union[str, Sequence[str], None] = 'd98c521b27f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_entities', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_entities', 'summary')
    # ### end Alembic commands ###
