"""remove academic_items and scoring

Revision ID: d98c521b27f0
Revises: 2db3e9a1c0f7
Create Date: 2026-04-29 15:51:14.448232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd98c521b27f0'
down_revision: Union[str, Sequence[str], None] = '2db3e9a1c0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_items_entity_type'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_merge_key'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_normalized_topic'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_source_email_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_status'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_subtype'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_uid'), table_name='academic_items')
    op.drop_table('academic_items')
    op.add_column('academic_entities', sa.Column('origin', sa.String(), server_default=sa.text("'system'"), nullable=False))
    op.create_index(op.f('ix_academic_entities_origin'), 'academic_entities', ['origin'], unique=False)
    op.drop_column('broadcasts', 'academic_score')
    op.drop_column('gmail_messages', 'academic_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_messages', sa.Column('academic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('broadcasts', sa.Column('academic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_academic_entities_origin'), table_name='academic_entities')
    op.drop_column('academic_entities', 'origin')
    op.create_table('academic_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_email_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('professor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('academic_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('snoozed_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_signals_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('merge_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_ai_processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subtype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('normalized_topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_items_pkey'))
    )
    op.create_index(op.f('ix_academic_items_uid'), 'academic_items', ['uid'], unique=False)
    op.create_index(op.f('ix_academic_items_subtype'), 'academic_items', ['subtype'], unique=False)
    op.create_index(op.f('ix_academic_items_status'), 'academic_items', ['status'], unique=False)
    op.create_index(op.f('ix_academic_items_source_email_id'), 'academic_items', ['source_email_id'], unique=False)
    op.create_index(op.f('ix_academic_items_normalized_topic'), 'academic_items', ['normalized_topic'], unique=False)
    op.create_index(op.f('ix_academic_items_merge_key'), 'academic_items', ['merge_key'], unique=False)
    op.create_index(op.f('ix_academic_items_id'), 'academic_items', ['id'], unique=False)
    op.create_index(op.f('ix_academic_items_entity_type'), 'academic_items', ['entity_type'], unique=False)
    # ### end Alembic commands ###
