"""add gmail_messages table

Revision ID: dd23fb267d0a
Revises: 82b5d159b592
Create Date: 2026-01-14 15:15:39.712453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd23fb267d0a'
down_revision: Union[str, Sequence[str], None] = '82b5d159b592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('gmail_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('internal_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_messages_gmail_id'), 'gmail_messages', ['gmail_id'], unique=True)
    op.create_index(op.f('ix_gmail_messages_uid'), 'gmail_messages', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_messages_uid'), table_name='gmail_messages')
    op.drop_index(op.f('ix_gmail_messages_gmail_id'), table_name='gmail_messages')
    op.drop_table('gmail_messages')
    # ### end Alembic commands ###
