"""add reauth fields to users

Revision ID: ded6d6cb85e3
Revises: 94c996b306fb
Create Date: 2026-04-06 18:55:17.364693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded6d6cb85e3'
down_revision: Union[str, Sequence[str], None] = '94c996b306fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reauth_required', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reauth_required_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reauth_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reauth_reason')
    op.drop_column('users', 'reauth_required_at')
    op.drop_column('users', 'reauth_required')
    # ### end Alembic commands ###
