"""Add watch_expiration field to GmailSyncStatus for Gmail Pub/Sub watch renewal tracking

Revision ID: fcc4b7702e5a
Revises: b58fdeed1b7e
Create Date: 2026-04-24 18:46:55.529094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc4b7702e5a'
down_revision: Union[str, Sequence[str], None] = 'b58fdeed1b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sync_status', sa.Column('watch_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sync_status', 'watch_expiration')
    # ### end Alembic commands ###
