name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t unidash-backend .

      - name: Stop old container
        run: |
          docker stop unidash-backend || true
          docker rm unidash-backend || true

      - name: Start new container
        run: |
          docker run -d \
          --name unidash-backend \
          -p 8000:8000 \
          unidash-backend