name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create Firebase credentials file
        run: |
          echo '${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}' > backend/credentials.json

      - name: Create environment variables file
        run: |
          echo '${{ secrets.PROD_ENVIRONMENT }}' > backend/.env.prod

      - name: Deploy backend stack with Redis
        working-directory: backend
        run: |
          docker compose -p unidash-prod -f docker-compose.prod.yml up -d --build --remove-orphans

      - name: Prune unused images
        run: docker image prune -f